### ISSUE TITLE
MOVENAME network edge False being interpreted as True

### ISSUE THREAD

**Issue by souvik1982** [CUASAS/pixel-gantry-control#77] opened 2023-02-21 22:10 UTC
gScript's MOVENAME command seems to interpret False in a graphMotion network edge to be true.
The issue does not exist in the graph visualizer.

**Comment by cfangmeier** [comment] 2023-02-22 20:05
I looked into this and I'm unable to reproduce this behavior. A couple things to check:

  1. Are you loading in any other config files that might have `graph_motion.edge.*` entries? Based on what I saw during our chat, I'm guessing the answer is no, but it's good to double check.
  2. The `out` tool rack positions are close enough that moving to one or the other from home may initially look the same until the gantry moves closer to the tool rack. Are you certain that the gantry was actually taking the wrong path?

**Comment by cfangmeier** [comment] 2023-08-01 20:58
Closing this pending verification that the issue still exists.

**Closed by cfangmeier** 2023-08-01 20:58 UTC
